### ISSUE TITLE
pboivin/twill-form-templates v0.1.3 requires area17/twill ^2.0 -> found area17/twill[2.0.0, ..., 2.x-dev] but it conflicts with your root composer.json require (^3.0).

### ISSUE THREAD

**Issue by michaeljcoyne** [pboivin/twill-form-templates#7]
Hi I am trying to upgrade to Twill 3.0 but get the error

pboivin/twill-form-templates v0.1.3 requires area17/twill ^2.0 -> found area17/twill[2.0.0, ..., 2.x-dev] but it conflicts with your root composer.json require (^3.0).

Will this not work with Twill 3?

**Comment by ifox** [comment]
Hi @michaeljcoyne this will definitely be compatible with Twill 3. It should mostly be about updating the composer requirement. I can submit a PR, unless you or @pboivin want to take care of it.

**Comment by michaeljcoyne** [comment]
Hi @ifox I don't have access - says it can't perform. I was just doing the PR from the twill-3 branch I have noticed is already there. So should be a case of just merging that small change in I guess if it is thant simple. Thanks.

**Comment by michaeljcoyne** [comment]
@ifox I have done a pull request on a forked repo which was essentially the same as @pboivin so may be quicker to approve that, although I havent tested.

**Comment by pboivin** [comment]
Thanks for the PR @michaeljcoyne! I'll tag a new release later today.
